### ISSUE TITLE
a11y_Tabs> Icon> A11y> 2 incomplete is appearing

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#517] opened 2022-02-14 10:10 UTC
**Describe the bug**
Tabs>> "2 incomplete" is appearing for "Icon". 

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--icon'
2. Click on 'Accessibility" add on
3. "2 incomplete" is appearing

**Expected behavior**
"0 incomplete" should appear for Tabs> Icon.

**Screenshots**
https://somup.com/c3n26QTcVY

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by silvalaura** [comment] 2022-08-05 14:58
Fixed indirectly. This is no longer an issue in the latest version: https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--icon
![image](https://user-images.githubusercontent.com/91160746/183104194-5f335e30-369f-4e38-bd09-1026e6b056bb.png)

**Closed by silvalaura** 2022-08-05 14:58 UTC
Labels: a11y

**Comment by Uditsingh67** [comment] 2022-08-08 04:23
The issue is fixed.
**Storybook Link :** https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--icon
**See Screen-cast :** http://somup.com/c3jjfqumJS
Thanks!

**Comment by Uditsingh67** [comment] 2022-08-30 07:47
Issue does not exist.
See Screen-cast : http://somup.com/c3jvimUld6
