### ISSUE TITLE
Documentation> Tabs> Blank page is appearing when clicks on "View Component API" button

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#460] opened 2022-02-11 08:00 UTC
**Describe the bug**
Blank page is appearing when clicks on "View Component API" button.

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/design/tabs/
2. Click on "View Component API" button
3. Verify the blank page

**Expected behavior**
COMPONENT API Tabs" page should appear when clicks on "View Component API" button.

**Screenshots**
https://somup.com/c3nQIdZNJ4

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-21 05:02
The issue is fixed.
See screen-cast: https://www.screenpresso.com/=502Gd
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-21 05:02 UTC
Labels: documentation
