### ISSUE TITLE
Documentation> Design Documentation link> "Not Found" error message is appearing upon launching

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#461] opened 2022-02-11 08:04 UTC
**Describe the bug**
"Not Found" error message is appearing upon launching the link "Design Documentation."

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api-intro/usage/#using_the_magma_theme
2. Click on "Design Documentation." link
3. Verify the message

**Expected behavior**
Appropriate document should appear upon launch the link.

**Screenshots**
https://somup.com/c3nQ23ZN7J

**Desktop :**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-22 06:09
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=7e2Df
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-22 06:09 UTC
Labels: documentation
