### ISSUE TITLE
Default a:hover color differs from Hyperlink

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#900] opened 2022-08-29 20:18 UTC
**Describe the bug**
Our Global Style for `a:hover` is also the global style for`a:focus`. This is causing anchor tags that don't use the Hyperlink component to have the wrong hover color

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/3.1.1/api/input/
2. Notice that the hover color is light blue (#0074b7) instead of light plurple (#5D65C)

**Expected behavior**
- The `a:hover` [Global Style](https://github.com/cengage/react-magma/blob/dev/packages/react-magma-dom/src/theme/GlobalStyles/index.tsx#L54-L57) color should be `primary400` to match the Hyperlink component.
- This needs to be fixed in the [landing page stylesheet](https://github.com/cengage/react-magma/blob/dev/website/react-magma-landing/static/styles.css#L42) as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/91160746/187290585-015c4e68-11e7-4722-9fd9-ccbd1f4fdbd2.png)

This was also noticed in [CESL](https://common-experience-library-design.apps.qa.ocf.cengage.io/?path=/story/components-annotationitem--bookmarks-annotation):
![image](https://user-images.githubusercontent.com/91160746/187293619-7813f48d-0585-4ecd-bf50-f3a82f7c5c35.png)

**Comment by silvalaura** [comment] 2022-09-12 21:13
**Testing notes**
- Look at storybook under the Hyperlink story (https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/hyperlink--default)
- Confirm in the docs site that links on the pages have the correct styling (https://next--upbeat-sinoussi-f675aa.netlify.app/api/hyperlink/)

**Comment by Uditsingh67** [comment] 2022-09-13 05:27
The issue is still reproducible.
See Screen-cast : http://somup.com/c3QIhOUvpH
Thanks!

**Comment by silvalaura** [comment] 2022-09-13 13:18
@Uditsingh67 It looks like the screencast is looking at the released URL instead of the dev version. Please re-test using https://next--upbeat-sinoussi-f675aa.netlify.app/api/input/. 

In the released version, the anchor hover color is #0074b7
![image](https://user-images.githubusercontent.com/91160746/189910676-a27fe337-6c04-4c81-8b99-9dcf2686cd90.png)

In the dev version, the anchor hover color is #5d65cb (as expected)
![image](https://user-images.githubusercontent.com/91160746/189910864-57fe64b3-5f35-43a0-a65b-e3175fd20e90.png)

**Comment by Uditsingh67** [comment] 2022-09-14 03:38
The issue is fixed on https://next--upbeat-sinoussi-f675aa.netlify.app/api/input/.
See Screen-cast : http://somup.com/c3Q2eAUxrN
Thanks!

**Closed by Uditsingh67** 2022-09-14 03:38 UTC
Labels: bug
