### ISSUE TITLE
Clicking on the scroll bar in the dropdown with fixed width closes the dropdown

### ISSUE THREAD

**Issue by EleanorKartyshova** [cengage/react-magma#297] opened 2021-06-23 09:32 UTC
**Steps to reproduce the behavior:**
1. Open the dropdown
2. Scroll down the list with scroll bar

**Expected behavior:**
The list is scrolled

**Desktop:**
windows10/chrome 91
windows10/edge 90
windows10/ff 89
mac os 10.15/safari 13
mac os 10.15/chrome 91

https://user-images.githubusercontent.com/72541410/123073253-ee79d000-d41e-11eb-9403-ccabb83f3338.mp4

**Comment by aaronmaturen** [comment] 2021-06-25 17:54
This is also affecting Checkboxes... from the open button to the menu we use an internal `menuRef` which seems to be added to the wrong element

**Comment by Uditsingh67** [comment] 2021-11-16 07:46
Not able to find the fixed width button please share the location of the button.

**Comment by Uditsingh67** [comment] 2022-04-12 03:19
The issue is fixed now the list is scrolled.
See Screen-cast : https://www.screenpresso.com/=93uFb
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-12 03:19 UTC
Labels: bug, react-magma-dom
