### ISSUE TITLE
Documentation> ProgressBar link> Link "ProgressBar" is navigating to incorrect location

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#469] opened 2022-02-11 10:13 UTC
**Describe the bug**
Link "ProgressBar" is navigating to incorrect location.

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api/loading-indicator/
2. Navigate to "Loading Indicator Props"
3. Click on link "ProgressBar"
4. Verify that link is navigating to "Inverse" heading instead of "ProgressBar"

**Expected behavior**
Link "ProgressBar" should navigate to appropriate location.

**Screenshots**
https://somup.com/c3nX6XZRem

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-21 05:09
The issue is fixed.
See Screen-cast: https://www.screenpresso.com/=bp9Xe
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-21 05:09 UTC
Labels: documentation
