### ISSUE TITLE
Tags documentation is missing prop table

### ISSUE THREAD

**Issue by greenervigil** [cengage/react-magma#703] opened 2022-05-17 18:59 UTC
**Describe the bug**
Documentation for tags is missing props tables.

**To Reproduce**
1. Go to Tag documentation 
2. Scroll down to Props tables
4. Props are missing

**Expected behavior**
Props tables should show all available props for the component. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16470877/168889589-53ac55ca-f695-4482-aa8c-e4faf7148365.png)

**Comment by silvalaura** [comment] 2022-06-16 16:41
Duplicate of #706

**Closed by silvalaura** 2022-06-16 16:41 UTC
Labels: testathon
