### ISSUE TITLE
Bug_IconButton> Icon Only/Animated Icon> 'textTransform' control prop> Preview is not getting changed upon selecting the 'textTransform' options. 

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#549] opened 2022-02-16 08:31 UTC
**Describe the bug**
Preview is not getting changed upon selecting the 'uppercase', and 'none' textTransform options for Icon Only and Animated Icon components.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/iconbutton--icon-only'
2. Click on 'Controls'
3. Select the 'textTransform' control prop
4. Select the 'uppercase', or 'none' options
5. Verify the preview

**Expected behavior**
'textTransform' control prop should not appear in controls as there is icon present on preview page instead of button.

**Screenshots**
https://somup.com/c3nDjTTetQ

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-12 05:35
The issue is fixed. now the 'textTransform' control prop is removed form Icon Only/Animated Icon.
See Screen-cast : https://www.screenpresso.com/=gZa2f
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-12 05:35 UTC
Labels: bug
