### ISSUE TITLE
Add support for 'DD/MM/YYYY' format to Datepicker

### ISSUE THREAD

**Issue by Brazhko** [cengage/react-magma#295] opened 2021-06-23 06:46 UTC
**Datepicker** component doesn't support '_DD/MM/YYYY_` format even if **I18nContext** object is changed ({"locale": enAU,  "dateFormat": "dd/MM/yyyy"}) - '_onBlur_' event handler resets value in the input or swaps day and month values.

Sandbox - https://codesandbox.io/s/react-magma-example-forked-4j57k?file=/example.tsx

**Comment by silvalaura** [comment] 2022-06-15 14:09
Duplicate of #748

**Closed** 2022-08-04 17:13 UTC
Labels: react-magma-dom, feature request

**Comment by Uditsingh67** [comment] 2022-08-09 10:00
The issue is fixed.
See Screen-cast: http://somup.com/c3jQQRuJKe
Thanks!

**Comment by Uditsingh67** [comment] 2022-08-31 07:30
Issue does not exist.
See Screen-cast : http://somup.com/c3jwivU2TR
