### ISSUE TITLE
Bug_Tag> On Delete With Icon> 'isInverse' control prop> Preview is not getting changed upon selecting the 'isInverse' control to 'True'.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#568] opened 2022-02-17 08:47 UTC
**Describe the bug**
Preview is not getting changed upon selecting the 'isInverse' control.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tag--on-delete-with-icon'
2. Click on 'Controls'
3. Select 'isInverse' control prop
4. Toggle it inro 'True'
5. Verify the preview

**Expected behavior**
Preview should get changed upon selecting the 'isInverse' control to 'True'.

**Screenshots**
https://somup.com/c3nbjEThlx

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-12 03:52
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=4WB4d
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-12 03:52 UTC
Labels: bug, help wanted
