### ISSUE TITLE
Documentation> Check out this PDF link> "Not Found" error message is appearing upon launching.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#458] opened 2022-02-11 07:42 UTC
**Describe the bug**
"Not Found" error message is appearing upon launching the link "Check out this PDF".

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/contribution-guidelines/
2. Click on "Check out this PDF" link
3. Verify the error

**Expected behavior**
Appropriate pdf should appear upon launching the link.

**Screenshots**
https://somup.com/c3nQQAZNtU

**Desktop:**
 - OS: [Win 10]
 - Browser [Chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-22 06:06
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=6ULPf
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-22 06:06 UTC
Labels: documentation
