### ISSUE TITLE
Data Grid styling with colored rows is showing rounded 

### ISSUE THREAD

**Issue by greenervigil** [cengage/react-magma#818] opened 2022-07-05 19:53 UTC
**Describe the bug**
On the DataGrid Component, the last row of the table is showing rounded when using row colors.  

**To Reproduce**
1. Go to Data Grid Component on both Storybook and in the Docs
2. Scroll down to 'row color'
3. See The last row is showing as rounded on the bottom only.

**Expected behavior**
The rounded edge should go only be on the pagination when it is selected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16470877/177404796-81f8a0af-1481-421d-b915-c1c31a1b4571.png)

**Comment by Uditsingh67** [comment] 2022-07-18 05:48
The issue is fixed in Storybook but still reproducible in React magma.
**See Screen-cast :** http://somup.com/c3iFhGuYTs

- RM Link : https://next--upbeat-sinoussi-f675aa.netlify.app/api/datagrid/
- Storybook Link : https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/docs/datagrid--colored-rows
Thanks!

**Closed** 2022-07-20 15:00 UTC

**Comment by hkrishna29** [comment] 2022-07-20 19:10
![Testing proof _818](https://user-images.githubusercontent.com/90398760/180062775-4a4c640d-7393-420c-bfb7-72e40fd06ddc.png)

 **the issue no longer exists on Win 10/Ch  103.0.5060.114**

**Comment by hkrishna29** [comment] 2022-07-20 19:10
https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datagrid--colored-rows
