### ISSUE TITLE
a11y_NativeSelect> Helper Message Inverse> A11y> 1 violations is appearing

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#506] opened 2022-02-14 09:05 UTC
**Describe the bug**
NativeSelect>> "1 violations" is appearing for "Helper Message Inverse". 

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/nativeselect--helper-message-inverse'
2. Click on 'Accessibility" add on
3. "1 violations" is appearing

**Expected behavior**
"0 violations" should appear for NativeSelect> Helper Message Inverse.

**Screenshots**
https://somup.com/c3n2QfZW9F

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-08-04 04:10
The issue is fixed.
See Screen-cast : http://somup.com/c3jffjuCpQ
Thanks!

**Comment by ccedrone** [comment] 2022-08-05 12:16
This was fixed via: [854](https://github.com/cengage/react-magma/pull/854)

**Closed by ccedrone** 2022-08-05 12:16 UTC
Labels: a11y

**Comment by Uditsingh67** [comment] 2022-08-30 07:58
Issue does not exist.
See Screen-cast : http://somup.com/c3jvi9UldN
