### ISSUE TITLE
a11y_Tabs> Icon Only> A11y> 1 incomplete is appearing

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#518] opened 2022-02-14 10:13 UTC
**Describe the bug**
Tabs>> "1 incomplete" is appearing for "Icon Only". 

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--icon-only'
2. Click on 'Accessibility" add on
3. "1 incomplete" is appearing

**Expected behavior**
"0 incomplete" should appear for Tabs> Icon Only.

**Screenshots**
https://somup.com/c3n26lTcV4

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by silvalaura** [comment] 2022-08-05 14:59
Fixed indirectly. This is no longer an issue in the latest version: https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--icon-only
![image](https://user-images.githubusercontent.com/91160746/183104464-1d83592d-f0f9-4e2d-af62-7c6354bf18b3.png)

**Closed by silvalaura** 2022-08-05 14:59 UTC
Labels: a11y

**Comment by Uditsingh67** [comment] 2022-08-08 04:25
The issue is fixed.
**Storybook Link :** https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--icon-only
**See Screen-cast :** http://somup.com/c3jjfZumd1
Thanks!

**Comment by Uditsingh67** [comment] 2022-08-30 07:48
Issue does not exist.
See Screen-cast : http://somup.com/c3jviJUldY
