### ISSUE TITLE
Bug_SchemaRenderer> Array> 'Add Item' button> Error message is appearing on preview screen when clicks on 'Add Item' button.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#574] opened 2022-02-17 10:53 UTC
**Describe the bug**
'Cannot read properties of undefined (reading 'map')' error message is appearing on preview screen when clicks on 'Add Item' button.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/schemarenderer--array'
2. Click on 'Add Item' button
3. Verify that error message is appearing on preview screen

**Expected behavior**
Error message should not appear on preview screen when clicks on 'Add Item' button.

**Screenshots**
https://somup.com/c3nb6sTh37

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-11 12:38
The issue is still Reproducible.
See Screen-cast : https://www.screenpresso.com/=EtxHd
Hence, Reopening the ticket.
Thanks!

**Comment by Uditsingh67** [comment] 2022-04-12 03:13
The Issue is fixed.
See Screen-cast : https://www.screenpresso.com/=vL26d
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-12 03:13 UTC
Labels: bug, help wanted
