### ISSUE TITLE
Documentation> Dropzone API> Headings are not appearing in left navigation panel.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#465] opened 2022-02-11 08:27 UTC
**Describe the bug**
Following headings are not appearing in left navigation panel:
- Basic Usage
- No Dragging
- Inverse
- Handle File Processing
- Deleting Files
- Processing Examples

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/api/dropzone/
2. Scroll the left navigation panel
3. Observe the API> Dropzone in left navigation panel
4. Verify that above mentioned headings are missing as compared with the heading present on Dropzone API page

**Expected behavior**
Headings are not appearing in navigation panel.

**Screenshots**
https://somup.com/c3n6XyZPZH

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-21 05:14
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=7Cibg
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-21 05:14 UTC
Labels: documentation
