### ISSUE TITLE
On MacOS/Safari The multi-select dropdown filter list is not getting closed upon clicking the DropdownButton

### ISSUE THREAD

**Issue by OlenaYashyna** [cengage/react-magma#1291] opened 2024-05-20 13:58 UTC
**Describe the bug**
Mac + Safari specific
On MacOS/Safari The multi-select dropdown filter list is not getting closed upon clicking the  DropdownButton

**To Reproduce**
1. Go to 'https://react-magma.cengage.com/version/4.2.0/api/dropdown/'
2. Click on DropdownButton to open/expand the Dropdown
3. Click on DropdownButton to close/collapse the Dropdown
4. See error, Dropdown menu is still opened

**Expected behavior**
The Dropdown should be closed in Safari upon clicking DropdownButton

**Desktop (please complete the following information):**
 - MacOS
 - Safari

**Comment by silvalaura** [comment] 2024-05-20 14:09
Duplicate of #1142

**Closed by silvalaura** 2024-05-20 14:09 UTC
