### ISSUE TITLE
Bug_Select> Multi> Error message is appearing on preview screen as compared with other components. 

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#562] opened 2022-02-17 05:04 UTC
**Describe the bug**
'Cannot read properties of undefined (reading 'filter')' error message is appearing for 'Multi'. However, text 'Example' with the dropdown box is appearing for other components of Select.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/select--multi'
2. Verify that error message is appearing on preview screen instead of text 'example' with the dropdown box

**Expected behavior**
Text 'Example' with the dropdown box should appear for 'Multi' as compared with other components.

**Screenshots**
https://somup.com/c3nbheTfSI

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Additional context**
Due to this error message, we are unable to verify the 'labelPosition' control prop.

**Comment by silvalaura** [comment] 2022-04-06 21:01
Storybook link: https://storybook-preview-626--upbeat-sinoussi-f675aa.netlify.app/?path=/story/accordion--default

**Comment by Uditsingh67** [comment] 2022-04-12 06:00
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=eqwtd
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-12 06:00 UTC
Labels: bug
