### ISSUE TITLE
Bug_Tabs> Icon Only> 'iconPosition' control prop> Content is appearing shifted when changing the 'iconPosition' control prop.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#564] opened 2022-02-17 06:53 UTC
**Describe the bug**
Content is appearing shifted when changing the 'iconPosition' control prop.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--icon-only'
2. Click on 'Controls'
3. Select the 'iconPosition' options
4. Verify that content is appearing shifted

**Expected behavior**
Content should not shift on changing the  'iconPosition' control prop
OR
'iconPosition' control should not appear under 'Controls' as 'Icon With Text' is not available on preview page.

**Screenshots**
https://somup.com/c3nb1sThfG

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Additional context**
We have observed that icons are not available on preview page.

**Comment by ccedrone** [comment] 2022-04-13 12:33
Per the shifting: cannot reproduce

"'iconPosition' control should not appear under 'Controls' as 'Icon With Text' is not available on preview page.":

Storybook consolidates the available props into that cluster and isn't necessarily a bug.

**Comment by silvalaura** [comment] 2022-04-13 13:18
I agree @ccedrone . Closing as "won't fix"

**Closed by silvalaura** 2022-04-13 13:18 UTC
Labels: bug
