### ISSUE TITLE
Documentation_ Design with React Magma button> "Not Found" error message is appearing upon launching

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#457] opened 2022-02-11 07:24 UTC
**Describe the bug**
"Not Found" error message is appearing upon launching the button "Design with React Magma".

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/
2. Click on "Design with React Magma" button
3. Verify the message

**Expected behavior**
Appropriate page should appear when clicks on button "Design with React Magma"

**Screenshots**
https://screencast-o-matic.com/watch/c3nQQlVDNgt

**Desktop :**
 - OS: [Win 10]
 - Browser [Chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-22 05:29
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=Tv8Kc
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-22 05:29 UTC
Labels: documentation
