### ISSUE TITLE
Documentation> Dropzone> "View Design Guidelines" button is not appearing to navigate back from API page to Guidelines page.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#459] opened 2022-02-11 07:55 UTC
**Describe the bug**
Button "View Design Guidelines" is not apearing when clicks on button "View Component API".

**To Reproduce**
1. Go to https://react-magma.cengage.com/version/2.5.7/design/dropzone/
2. Click on "View Component API" button
3. Verify that "View Design Guidelines" button is not appearing to navigate back from API page to Guidelines page

**Expected behavior**
Button "View Design Guidelines" should appear when clicks on button "View Component API"

**Screenshots**
https://somup.com/c3nQXVZN4k

**Desktop :**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Additional context**
We have observed that "Dropzone" is appearing under Design guidelines and API both. When we clicks on "View Component API" button, the API page appears. However, user is unable to navigate back to Guidelines page as "View Design Guidelines" button is missing.

**Comment by Uditsingh67** [comment] 2022-04-21 05:04
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=ES7J
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-21 05:04 UTC
Labels: documentation
