### ISSUE TITLE
Container>Default/Inverse/Max width/Gutters> 1 incomplete is appearing when user moves control tab to Accessibility tab.

### ISSUE THREAD

**Issue by Uditsingh67** [cengage/react-magma#884] opened 2022-08-18 07:56 UTC
**Describe the bug**
Default/Inverse/Max width/Gutters> 1 incomplete is appearing when user moves control tab to Accessibility tab.

**To Reproduce**
**Steps to reproduce the behavior:**

1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/container--default
2. Click on the Control tab 
3. Click on the Accessibility tab
4. And Verify

**Expected behavior**
0 incomplete should appear when user moves control tab to Accessibility tab.

**Screenshots**
http://somup.com/c3jFiduR8n

**Desktop:**

- OS: [Win 10]
- Browser [chrome]
- Version [Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by silvalaura** [comment] 2022-08-18 14:37
Duplicate of https://github.com/cengage/react-magma/issues/493-- it's an issue with the accessibility plugin in Storybook. No plans to fix.

**Closed by silvalaura** 2022-08-18 14:37 UTC
Labels: storybook
