### ISSUE TITLE
Bug_Tag> Disabled/Disabled Inverse> All control prop> Preview is not getting changed upon selecting the 'size', 'color', 'disabled', and 'isInverse' controls.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#565] opened 2022-02-17 08:12 UTC
**Describe the bug**
Preview is not getting changed upon selecting the 'size', 'color', 'disabled', and 'isInverse' controls.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tag--disabled'
2. Click on 'Controls'
3. Change in any control prop say, 'size'
4. Change the size medium to small
5. Verify the preview

**Expected behavior**
Preview should get changed upon selecting the 'size', 'color', 'disabled', and 'isInverse' controls.

**Screenshots**
https://somup.com/c3nbjXTh6c

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-12 03:49
The issue is still reproducible. not able to change the color of 'Disabled/Disabled Inverse'.
See Screen-cast : https://www.screenpresso.com/=6bqvb
Hence, Reopening the ticket.
Thanks!

**Comment by silvalaura** [comment] 2022-04-12 17:10
@Uditsingh67 I believe this is functioning as designed. In the gif below we can see that the color of the first tag does get updated. When the disabled state is true, it doesn't appear to change because the disabled color is the same for the various tag colors:
![chrome-capture-2022-3-12](https://user-images.githubusercontent.com/91160746/163016677-7d9ea32f-fe86-48ab-a3fc-94b654e0364d.gif)

**Comment by Uditsingh67** [comment] 2022-04-14 04:09
As per the above comment, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-14 04:09 UTC
Labels: bug, help wanted
