### ISSUE TITLE
Bug_Accordion> Expand Collapse All> Control prop 'iconPosition'> icon position is not getting changed

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#532] opened 2022-02-15 10:40 UTC
**Describe the bug**
Arrow icons does not get changed upon selecting the 'right', 'left' and 'none' options.

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/accordion--expand-collapse-all'
2. Click on 'Controls'
3. Select the iconPosition
4. Verify that icon position is not getting changed accordingly

**Expected behavior**
icon position should get changed upon selecting the 'right', 'left' and 'none' options.

**Screenshots**
https://somup.com/c3no6kTVsc

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-21 04:18
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=9F0cf
Hence, Closing the ticket.
Thanks!

**Closed** 2022-04-21 04:18 UTC
Labels: bug
