### ISSUE TITLE
a11y_Tabs> Default> A11y> 2 incomplete is appearing

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#516] opened 2022-02-14 10:08 UTC
**Describe the bug**
Tabs>> "2 incomplete" is appearing for "Default". 

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--default'
2. Click on 'Accessibility" add on
3. "2 incomplete" is appearing

**Expected behavior**
"0 incomplete" should appear for Tabs> Default.

**Screenshots**
https://somup.com/c3n26jTcVl

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by silvalaura** [comment] 2022-08-05 15:00
Fixed indirectly. This is no longer an issue in the latest version: https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--default

![image](https://user-images.githubusercontent.com/91160746/183104729-136a2c73-c4d2-42f3-9a82-227af79df04e.png)

**Closed by silvalaura** 2022-08-05 15:00 UTC
Labels: a11y

**Comment by Uditsingh67** [comment] 2022-08-08 04:32
The Issue is fixed.
**Storybook Link** : https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabs--default
**Screen-cast :** http://somup.com/c3jjfwumd0
Thanks!

**Comment by Uditsingh67** [comment] 2022-08-30 07:42
Issue does not exist.
See Screen-cast : http://somup.com/c3jvipUlJB
