### ISSUE TITLE
Documentation> "Hyperlink Props" link> Link "Hyperlink Props" is navigating to incorrect location

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#485] opened 2022-02-14 06:19 UTC
Describe the bug
Link "Hyperlink Props" is navigating to heading "Inverse" instead of heading "Search Props"

To Reproduce

1.Go to https://react-magma.cengage.com/version/2.5.7/patterns/header/#call_to_action
2.Click on "Hyperlink Props" link
3. Verify that link is navigating to heading "Inverse"

Expected behavior
Link "Hyperlink Props" should navigate to correct location.

Screenshots:
https://somup.com/c3n21bZWJ1

Desktop:
OS: [Win 10]
Browser [chrome]
Version [Chrome version: Version  98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-22 05:27
The issue is fixed.
See Screen-cast : https://www.screenpresso.com/=JkUte
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-22 05:27 UTC
Labels: documentation
