### ISSUE TITLE
Bug_Spacer> Default> Preview page is appearing blank by default.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#557] opened 2022-02-16 11:45 UTC
**Describe the bug**
Preview page is appearing blank by default.

**To Reproduce**

1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/spacer--default'
2. Verify the preview page

**Expected behavior**
Preview page should not appear blank.

**Screenshots**
https://somup.com/c3nDXGTep5

**Desktop:**

OS: [Win 10]
Browser [chrome]
Version [Version 98.0.4758.82 (Official Build) (64-bit)]

Additional context
We are unable to test the 'size' and 'axis' control prop as preview page is appearing blank.

**Comment by silvalaura** [comment] 2022-03-31 20:29
@orion-cengage @ccedrone How do we want to solve for this? The page looks empty because spacers are "white" space. Do we want to add a color for the purpose of the preview so it doesn't look broken? or delete the default story all together? Or, close this bug because _technically_ it's functioning as designed?

**Comment by ccedrone** [comment] 2022-04-01 12:23
It's technically not a bug to me either, however we could add a background color in this instance just so the "Default" state is preserved. What do you think?

**Comment by silvalaura** [comment] 2022-04-06 14:25
We have added a new feature to Storybook that allows you to measure and see spaces:
![image](https://user-images.githubusercontent.com/91160746/161997234-2921e9b5-2a54-42bd-9d5a-62696b793cf5.png)

https://storybook-preview-619--upbeat-sinoussi-f675aa.netlify.app/?path=/story/spacer--default&globals=measureEnabled:true

This shows that although the page appears empty, the spacer component is actually there and behaving as expected. I don't think there's anything else that needs to be done, so closing as won't fix.

**Closed by silvalaura** 2022-04-06 14:25 UTC
Labels: bug
