### ISSUE TITLE
Input with long placeholder has too much padding

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#955] opened 2022-11-02 14:23 UTC
**Describe the bug**
Inputs with long placeholders make it obvious that our inputs have too much right padding. This appears to be the case for all inputs, not just ones using icons on the right

Line: https://github.com/cengage/react-magma/blob/dev/packages/react-magma-dom/src/components/InputBase/index.tsx#L196

**To Reproduce**
1. Go to Input
2. Increase the placeholder text
3. Notice it's cut off

**Expected behavior**
Padding is appropriate for the input, and does not cover the input text

**Screenshots**
![image](https://user-images.githubusercontent.com/91160746/199513516-170d6826-0afa-4422-b9f1-edca88ac127b.png)
![image](https://user-images.githubusercontent.com/91160746/199513644-a0c13817-6386-42ec-bcef-686e01f868c4.png)
![image](https://user-images.githubusercontent.com/91160746/199514455-2aa72e07-0748-459c-bb92-f7b8862ef295.png)

**How to test**
1. Confirm inputs with a combination of props has the correct spacing.
- Try making the page smaller for smaller inputs and inserting long text.
- Try long placeholder text.
- Try with and without isClearable.
- Try the different icon positions
- etc...
2. Confirm all input types:
- Search
- Combobox
- DatePicker
3. It looks like the following components do not support isClearable, so these can be skipped
- TimePicker
- PasswordInput

**Comment by Uditsingh67** [comment] 2022-11-16 05:00
The issue is still reproducible.
**See Screen-cast :** http://somup.com/c3XDhcv9nA
Hence, Closing the ticket.
Thanks!

**Closed** 2022-11-17 20:19 UTC
Labels: bug, react-magma-dom

**Comment by Uditsingh67** [comment] 2022-11-21 05:49
The issue is fixed.
See Screen-cast : http://somup.com/c3XrhJwnIe
Thanks!
