### ISSUE TITLE
Bug_Accordion> Expand Collapse All> Control prop 'isInverse'> Preview is not getting changed upon toggling the True/False

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#533] opened 2022-02-15 10:53 UTC
**Describe the bug**
Dark background and light text is not displayed when 'isInverse' is 'True'.

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/accordion--expand-collapse-all'
2. Click on 'Controls'
3. Select the 'isInverse' control prop
4. Toggle it into 'True/False'
5. Verify that preview is not getting changed

**Expected behavior**
Dark background and light text should display when 'isInverse' is 'True'.

**Screenshots**
https://somup.com/c3no6pTVs1

**Desktop :**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by Uditsingh67** [comment] 2022-04-21 04:56
The issue is fixed.
see screen-cast : https://www.screenpresso.com/=irbac
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-21 04:56 UTC
Labels: bug
