### ISSUE TITLE
Documentation> "Optional Header"> Incorrect navigation is appearing when clicks on "Optional Header" second link.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#487] opened 2022-02-14 07:08 UTC
Describe the bug
Second "Optional Header" navigation present in left navigation panel is navigating to first heading.

To Reproduce

1. Go to https://react-magma.cengage.com/version/2.5.7/api/use-focus-lock/
2. Click on first "Optional Header" navigation present on left navigation panel 
3. Observe that appropriate navigation is appearing
4. Now, click on second "Optional Header" navigation present on left navigation panel
5. Verify that second "Optional Header" is not navigating to second heading

Expected behavior
Second "Optional Header" should navigate to second heading instead of the first heading.

Screenshots
https://somup.com/c3n2icZWKU

Desktop:

OS: [Win 10]
Browser [chrome]
Version [Chrome version: Version 98.0.4758.81 (Official Build) (64-bit)]

**Additional context**
We have observed that there are 2 "Optional Header" headings present on the left navigation panel and on the content page. When we click on the second "Optional Header", it is navigating to the first heading instead of the second heading.

**Comment by Uditsingh67** [comment] 2022-04-22 06:03
The issue is fixed.
see Screen-cast: https://www.screenpresso.com/=W4ref
Hence, Closing the ticket.
Thanks!

**Closed by Uditsingh67** 2022-04-22 06:03 UTC
Labels: documentation
