### ISSUE TITLE
Toast / Auto-dismiss - Have to click twice to dismiss

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#240] opened 2021-04-15 14:08 UTC
Looks like this bug was introduced in 2.3.10.

The problem appears to only exist on toasts that auto-dismiss.  You have to click twice to manually dismiss.  The first click only puts focus on the dismiss button.

**Comment by jamiesmyln** [comment] 2021-08-03 14:20
This has something to do with the browser cache - I think - since a hard refresh fixes the problem and we are already handling state properly. It's difficult to reproduce.

**Comment by rcgillet** [comment] 2021-08-30 15:00
Fixed in version 2.5.1 along with another `StyledButton` change.

**Closed by rcgillet** 2021-08-30 15:00 UTC
